.local/bin: Workaround setuptools clash with Debian patches
Debian patches setuptools/distutils, but not the distutils copy embedded
in setuptools, so https://github.com/pypa/pip/issues/6264 results in

    AttributeError: install_layout

Force SETUPTOOLS_USE_DISTUTILS=stdlib until (if ever) the issue is resolved.